### PR TITLE
feat: Fix floating promises in tests and index.js. Added tslint rule …

### LINKED ISSUE #157: Unit tests Erroring Out without throwing errors
## Expected Behavior
I was working on a PR for something and noticed that there are some unit tests which are very broken but the jest tests are still passing.

image

image

```
expect(async () => await searchMonitors("queryString", "apikey", "appkey")).rejects.toThrowError(
      "Could not perform request due to invalid authentication",
    )
```

will not throw an error and will just pass.

in fact it's throwing an error as is but jest won't throw it.

```
Expected substring: "Could not perform request due to invalid authentication"
Received message:   "response.json is not a function"
```

I would fix it, but I am fairly time poor.

When you switch it to the proper syntax eg. this it will fail properly
```
await expect(searchMonitors("queryString", "apikey", "appkey")).rejects.toThrowError(
      "Could not perform request due to invalid authentication",
);
```

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Serverless Framework version: 
  - Datadog Serverless Plugin version: 
  - Lambda function runtime (Python 3.7, Node 10, etc.): 
  
## Stacktrace
  
  ```
  Paste here
  ```

### PR DESCRIPTION
**Pull request by astuyve**
…to prevent floating promises. Throw errors from hanldeMonitorsApiResponse, as we cannot continue. Fix/update tests

### What does this PR do?

closes #157 

### Motivation

Our business logic was to log an error, but not halt execution. Coupled with the fact that a number of our tests were missing `awaits`, our suite wasn't failing when it should have been.

This change:
1. Throws errors in `handleMonitorsApiResponse` instead of logging them, to halt execution (as we cannot continue)
2. Fixes missing `await`ing of promises in tests
3. Fixes (perhaps critical) missing `await` of promises in `index.ts`.
4. Adds a `tslint` rule `no-dangling-promises` to prevent this
5. Updates assertions to account for `handleMonitorsApiResponse` new behavior
6. Adds a comment to address a future refactor that I don't have time for ATM.

### Testing Guidelines

- [x] Automated testing
- [ ] Manual exercising of the `createMonitors` functionality. TODO!

### Types of changes

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Misc (docs, refactoring, dependency upgrade, etc.)

### Check all that apply

- [x] This PR's description is comprehensive
- [ ] This PR contains breaking changes that are documented in the description
- [ ] This PR introduces new APIs or parameters that are documented and unlikely to change in the foreseeable future
- [ ] This PR impacts documentation, and it has been updated (or a ticket has been logged)
- [x] This PR's changes are covered by the automated tests
- [ ] This PR collects user input/sensitive content into Datadog

### CODE REVIEW

File: src/monitor-api-requests.ts [hunk 1]
```diff
@@ -64,6 +64,12 @@ export async function deleteMonitor(monitorId: number, monitorsApiKey: string, m
   return response;
 }
 
+/**
+ * TODO - refactor handleMonitorsApiResponse into this module
+ * and use it here instead of throwing an error
+ *
+ * This is done because getExistingMonitors calls searchMonitors
+ */
```
Comment (nhinsch) [inline src/monitor-api-requests.ts:72]: Nit: I wouldn't bother adding a TODO to the codebase -- instead I would either add a ticket in Jira, or accept that this is unlikely to be done any time soon. In my experience TODOs in code bases tend to hang out for a long time and just confuse the issue. They can also go out of date over time.

File: tslint.json [hunk 2]
```diff
@@ -5,6 +5,7 @@
     "variable-name": {
       "options": ["allow-leading-underscore"]
     },
+    "no-floating-promises": true,
```
Comment (nhinsch) [inline tslint.json:8]: 🙏

**Review by nhinsch — APPROVED** [review]
LGTM

I would nix the TODO comment

File: src/monitor-api-requests.ts (hunk 1 above)
Comment (astuyve) [reply src/monitor-api-requests.ts:72]: Oh. My intention was to make this an issue in Github and tag it as `hacktoberfest`, `good first issue` in a few weeks. :)
